# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
# Suggests: BiocStyle, GenomicFeatures, edgeR, org.Hs.eg.db, TxDb.Hsapiens.UCSC.hg19.knownGene
schema_version: 1

context:
  version: 1.36.1
  name: groHMM
  bioc: 3.18

package:
  name: bioinfoorphanage-${{ name|lower }}
  version: ${{ version }}

source:
  path: ..

build:
  number: 1
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - bioconductor-genomeinfodb >=1.38.0,<1.39.0
    - bioconductor-genomicalignments >=1.38.0,<1.39.0
    - bioconductor-genomicranges >=1.54.0,<1.55.0
    - bioconductor-iranges >=2.36.0,<2.37.0
    - bioconductor-rtracklayer >=1.62.0,<1.63.0
    - bioconductor-s4vectors >=0.40.0,<0.41.0
    - r-base
    - r-mass
  run:
    - bioconductor-genomeinfodb >=1.38.0,<1.39.0
    - bioconductor-genomicalignments >=1.38.0,<1.39.0
    - bioconductor-genomicranges >=1.54.0,<1.55.0
    - bioconductor-iranges >=2.36.0,<2.37.0
    - bioconductor-rtracklayer >=1.62.0,<1.63.0
    - bioconductor-s4vectors >=0.40.0,<0.41.0
    - r-base
    - r-mass
  build:
    - ${{ compiler('c') }}
    - make
  run_exports: ${{ pin_subpackage("bioinfoorphanage-grohmm", upper_bound="x.x") }}

tests:
  - script:
      - R -e "library('${{ name }}')"

about:
  license: GPL-3.0-only
  summary: GRO-seq Analysis Pipeline
  description: A pipeline for the analysis of GRO-seq data.
  # FIXME license_file: ${{ env.get("PREFIX") }}/lib/R/share/licenses/GPL-3
  homepage: https://bioconductor.org/packages/${{ bioc }}/bioc/html/${{ name }}.html

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - biotools:${{ name|lower }}
