name: Package

on: [push]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.14
        with:
          build-args: -c conda-forge -c bioconda
      - run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix "${pkg}"
          done
        env:
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
          PREFIX_CHANNEL: "https://repo.prefix.dev/bioinformaticsorphanage"
